"""Initial tables for analytics service

Revision ID: e5df3838f4cd
Revises: 
Create Date: 2025-02-25 23:41:20.427840

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e5df3838f4cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_link', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_short_link'), 'analytics', ['short_link'], unique=False)
    op.create_index(op.f('ix_analytics_updated_at'), 'analytics', ['updated_at'], unique=False)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analytics_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analytics_id'], ['analytics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clicks_city'), 'clicks', ['city'], unique=False)
    op.create_index(op.f('ix_clicks_country'), 'clicks', ['country'], unique=False)
    op.create_index(op.f('ix_clicks_id'), 'clicks', ['id'], unique=False)
    op.create_index(op.f('ix_clicks_ip'), 'clicks', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clicks_ip'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_country'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_city'), table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_analytics_updated_at'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_short_link'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
