apiVersion: v1
kind: ConfigMap
metadata:
  namespace: url-shortener
  name: shortener-config
data:
  SERVICE_PORT: "8000"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  ANALYTICS_SERVICE_GRPC: "analytics-service:50051"
