apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
  namespace: url-shortener
  labels:
    app: shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      containers:
      - name: shortener
        image: gcr.io/url-shortener/shortener:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: shortener-db-url
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: shortener-config
              key: ENVIRONMENT
