apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortener-public-ingress
  namespace: url-shortener
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      # Short URL redirects (public) - handles short URLs
      - path: /s/(.*)
        pathType: Prefix
        backend:
          service:
            name: shortener-service
            port:
              number: 80


      # Frontend (public) - serves the UI - CATCH-ALL MUST BE LAST
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
