apiVersion: v1
kind: ServiceAccount
metadata:
  name: url-shortener-sa
  namespace: url-shortener
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: url-shortener-role
  namespace: url-shortener
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: url-shortener-rolebinding
  namespace: url-shortener
subjects:
- kind: ServiceAccount
  name: url-shortener-sa
  namespace: url-shortener
roleRef:
  kind: Role
  name: url-shortener-role
  apiGroup: rbac.authorization.k8s.io