apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: url-shortener
  labels:
    app: analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: gcr.io/url-shortener/analytics:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: analytics-db-url
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: analytics-config
              key: ENVIRONMENT
