name: Type Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [shortener, analytics]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.service }}-${{ hashFiles(format('{0}/requirements.txt', matrix.service)) }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.service }}-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ matrix.service }}/requirements.txt

    - name: Run mypy
      run: |
        cd ${{ matrix.service }}
        mypy .
